# Generated by Django 4.0.2 on 2022-03-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quanity_as_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
