# Generated by Django 4.0.2 on 2022-03-04 13:25

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient_quanity_as_float'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quanity_as_float',
            new_name='quantity_as_float',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quanity',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[recipes.validators.validate_unit_of_measure]),
        ),
    ]
